// GENERATED by scripts/espn-trades-import.mjs — do not edit by hand.
// Source: ESPN league 803871539. Imported 2026-09-03.
//
// Accepted trades from ESPN's activity feed, recorded from the 2025/26 season onward. Each side lists the manager and the players they
// received in the deal.

import type { Trade } from '@/lib/types';

export const TRADES: Trade[] = [];
