// GENERATED by scripts/espn-import.mjs --live — do not edit by hand.
// Source: ESPN league 803871539, in-progress season 2027. Imported 2026-09-07.
//
// The live/upcoming season: ESPN's real fixtures, division split and running
// ladder. NOT part of the completed IMPORTED_SEASONS, so it never reaches the
// history, records or all-time stats. Re-run the import to refresh scores and
// pick up any fixture changes.

import type { LiveSeason } from '@/lib/data/imported';

export const liveSeason: LiveSeason = {
  "id": "2026-27",
  "espnSeasonId": 2027,
  "label": "2026/27",
  "leagueName": "Horn Pub Ligue 1",
  "regularSeasonWeeks": 19,
  "playoffTeams": 6,
  "started": false,
  "importedAt": "2026-09-07T21:09:31.495Z",
  "conferences": [
    {
      "id": "0",
      "name": "East"
    },
    {
      "id": "1",
      "name": "West"
    }
  ],
  "fixtures": [
    {
      "round": 1,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 1,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 1,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 1,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 1,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 1,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 2,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 3,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 4,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 5,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 6,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 7,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 8,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 9,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 10,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 11,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 12,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 13,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 14,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 15,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 16,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 17,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "aaron",
      "homeScore": 0,
      "awayId": "daniel",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "andrew",
      "homeScore": 0,
      "awayId": "izzy",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "jason",
      "homeScore": 0,
      "awayId": "luke",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "laven",
      "homeScore": 0,
      "awayId": "dylan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "nathan",
      "homeScore": 0,
      "awayId": "tyler",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 18,
      "homeId": "tuan",
      "homeScore": 0,
      "awayId": "ryan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "daniel",
      "homeScore": 0,
      "awayId": "andrew",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "dylan",
      "homeScore": 0,
      "awayId": "aaron",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "izzy",
      "homeScore": 0,
      "awayId": "jason",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "luke",
      "homeScore": 0,
      "awayId": "nathan",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "ryan",
      "homeScore": 0,
      "awayId": "laven",
      "awayScore": 0,
      "winner": "undecided"
    },
    {
      "round": 19,
      "homeId": "tyler",
      "homeScore": 0,
      "awayId": "tuan",
      "awayScore": 0,
      "winner": "undecided"
    }
  ],
  "standings": [
    {
      "managerId": "ryan",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "andrew",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "jason",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "dylan",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "daniel",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "tuan",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "izzy",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "nathan",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "tyler",
      "conferenceId": "0",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "laven",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "luke",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    },
    {
      "managerId": "aaron",
      "conferenceId": "1",
      "wins": 0,
      "losses": 0,
      "ties": 0,
      "pointsFor": 0,
      "pointsAgainst": 0,
      "ladderPosition": 0
    }
  ]
};
