import { STAT_ROWS } from '@/lib/data/espn-stats';

/**
 * The 2026 Stats Board.
 *
 * Real last-season (2025-26) actuals from ESPN — the "2026 STATISTICS" set —
 * scored in our league. This is fact, not projection: total and average fantasy
 * points plus the full per-game stat line, straight from ESPN. It's the board
 * you actually draft off, because the best predictor of next year is what a
 * player just did.
 *
 * Data is generated by scripts/espn-stats-import.mjs into lib/data/espn-stats.ts.
 */

export type Position = 'PG' | 'SG' | 'SF' | 'PF' | 'C';

export type StatRow = {
  id: string;
  espnId: number;
  name: string;
  team: string;
  pos: Position;
  /** ESPN's preseason draft rank (context only). */
  espnRank: number;
  /** ESPN injury status string (ACTIVE / OUT / DAY_TO_DAY …). */
  injuryStatus: string;
  /** False when the player has no last-season actuals (missed the year). */
  hasData: boolean;
  /** Season total fantasy points, our scoring. */
  totalFpts: number;
  /** Per-game fantasy points (total / games). */
  avgFpts: number;
  /** Rank by avgFpts across players with data (1 = best). 0 = no data. */
  avgRank: number;
  /** Rank by totalFpts across players with data (1 = best). 0 = no data. */
  totalRank: number;
  gp: number;
  min: number;
  fgPct: number;
  ftPct: number;
  tpm: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  to: number;
  pts: number;
  /** Assist-to-turnover ratio (derived). */
  ato: number;
};

export const STATS: StatRow[] = STAT_ROWS;

export const STATS_MAP: Record<string, StatRow> = Object.fromEntries(STATS.map((r) => [r.id, r]));

/** Players who actually logged games last season. */
export const STATS_WITH_DATA = STATS.filter((r) => r.hasData);
