// GENERATED by scripts/espn-import.mjs — do not edit by hand.
// Source: ESPN league 803871539, season 2022. Imported 2026-08-31.
//
// Team names, seeds and final placings come straight from ESPN. Everything the
// site displays is derived from the matchup list below.

import type { ImportedSeason } from '@/lib/data/imported';

export const season: ImportedSeason = {
  "id": "2021-22",
  "espnSeasonId": 2022,
  "label": "2021/22",
  "leagueName": "Horn Pub Ligue 1",
  "scoringType": "H2H_POINTS",
  "regularSeasonWeeks": 18,
  "playoffTeams": 6,
  "teams": [
    {
      "managerId": "ryan",
      "espnTeamId": 1,
      "teamName": "Boston Long Cocks",
      "ladderPosition": 1,
      "espn": {
        "wins": 15,
        "losses": 3,
        "ties": 0,
        "pointsFor": 26494,
        "pointsAgainst": 23359,
        "finalRank": 1
      }
    },
    {
      "managerId": "laven",
      "espnTeamId": 11,
      "teamName": "Bangholme Billygoats",
      "ladderPosition": 2,
      "espn": {
        "wins": 15,
        "losses": 3,
        "ties": 0,
        "pointsFor": 25436,
        "pointsAgainst": 22628,
        "finalRank": 2
      }
    },
    {
      "managerId": "daniel",
      "espnTeamId": 5,
      "teamName": "Frederick Rise Creampies",
      "ladderPosition": 3,
      "espn": {
        "wins": 11,
        "losses": 7,
        "ties": 0,
        "pointsFor": 24501,
        "pointsAgainst": 22905,
        "finalRank": 4
      }
    },
    {
      "managerId": "andrew",
      "espnTeamId": 2,
      "teamName": "Monash  Hospital",
      "ladderPosition": 4,
      "espn": {
        "wins": 10,
        "losses": 8,
        "ties": 0,
        "pointsFor": 25139,
        "pointsAgainst": 23903,
        "finalRank": 3
      }
    },
    {
      "managerId": "tyler",
      "espnTeamId": 10,
      "teamName": "King Cade",
      "ladderPosition": 5,
      "espn": {
        "wins": 9,
        "losses": 9,
        "ties": 0,
        "pointsFor": 23746,
        "pointsAgainst": 22867,
        "finalRank": 6
      }
    },
    {
      "managerId": "jason",
      "espnTeamId": 3,
      "teamName": "Big Bunda Co. Bunda",
      "ladderPosition": 6,
      "espn": {
        "wins": 9,
        "losses": 9,
        "ties": 0,
        "pointsFor": 23968,
        "pointsAgainst": 23952,
        "finalRank": 5
      }
    },
    {
      "managerId": "izzy",
      "espnTeamId": 7,
      "teamName": "HP AIRBALLERS",
      "ladderPosition": 7,
      "espn": {
        "wins": 7,
        "losses": 11,
        "ties": 0,
        "pointsFor": 23600,
        "pointsAgainst": 24553,
        "finalRank": 7
      }
    },
    {
      "managerId": "tuan",
      "espnTeamId": 6,
      "teamName": "GOOK CENTRAL GOOKIE",
      "ladderPosition": 8,
      "espn": {
        "wins": 6,
        "losses": 12,
        "ties": 0,
        "pointsFor": 23038,
        "pointsAgainst": 23895,
        "finalRank": 8
      }
    },
    {
      "managerId": "titian",
      "espnTeamId": 4,
      "teamName": "Minefield  Brickcity",
      "ladderPosition": 9,
      "espn": {
        "wins": 4,
        "losses": 14,
        "ties": 0,
        "pointsFor": 20304,
        "pointsAgainst": 24679,
        "finalRank": 10
      }
    },
    {
      "managerId": "nathan",
      "espnTeamId": 9,
      "teamName": "The Bear Cave",
      "ladderPosition": 10,
      "espn": {
        "wins": 4,
        "losses": 14,
        "ties": 0,
        "pointsFor": 20105,
        "pointsAgainst": 23590,
        "finalRank": 9
      }
    }
  ],
  "matchups": [
    {
      "week": 1,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1308,
      "awayId": "tuan",
      "awayScore": 1083
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1225,
      "awayId": "laven",
      "awayScore": 1241
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 851,
      "awayId": "tyler",
      "awayScore": 1231
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1188,
      "awayId": "nathan",
      "awayScore": 1122
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1003,
      "awayId": "jason",
      "awayScore": 1291
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1475,
      "awayId": "ryan",
      "awayScore": 1665
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1401,
      "awayId": "tuan",
      "awayScore": 1305
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1207,
      "awayId": "jason",
      "awayScore": 1789
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1079,
      "awayId": "daniel",
      "awayScore": 1341
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1415,
      "awayId": "andrew",
      "awayScore": 1560
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1415,
      "awayId": "tuan",
      "awayScore": 1285
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1870,
      "awayId": "izzy",
      "awayScore": 1375
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1607,
      "awayId": "andrew",
      "awayScore": 1480
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1320,
      "awayId": "nathan",
      "awayScore": 1313
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1372,
      "awayId": "laven",
      "awayScore": 1433
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1791,
      "awayId": "andrew",
      "awayScore": 1817
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1389,
      "awayId": "ryan",
      "awayScore": 1262
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1431,
      "awayId": "izzy",
      "awayScore": 1468
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1573,
      "awayId": "tuan",
      "awayScore": 1248
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1297,
      "awayId": "daniel",
      "awayScore": 1390
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1781,
      "awayId": "nathan",
      "awayScore": 1171
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1361,
      "awayId": "laven",
      "awayScore": 1421
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1224,
      "awayId": "daniel",
      "awayScore": 1222
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1389,
      "awayId": "izzy",
      "awayScore": 1467
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1605,
      "awayId": "tyler",
      "awayScore": 1536
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1361,
      "awayId": "jason",
      "awayScore": 1531
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1336,
      "awayId": "andrew",
      "awayScore": 1515
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1248,
      "awayId": "nathan",
      "awayScore": 1296
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1132,
      "awayId": "tyler",
      "awayScore": 1418
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1437,
      "awayId": "ryan",
      "awayScore": 1172
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1330,
      "awayId": "nathan",
      "awayScore": 1442
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1215,
      "awayId": "laven",
      "awayScore": 1222
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1374,
      "awayId": "tuan",
      "awayScore": 1295
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1460,
      "awayId": "tyler",
      "awayScore": 1383
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 804,
      "awayId": "andrew",
      "awayScore": 1588
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1417,
      "awayId": "daniel",
      "awayScore": 1538
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1517,
      "awayId": "andrew",
      "awayScore": 1252
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1260,
      "awayId": "tuan",
      "awayScore": 1361
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 1019,
      "awayId": "ryan",
      "awayScore": 1469
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1421,
      "awayId": "jason",
      "awayScore": 1312
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1300,
      "awayId": "daniel",
      "awayScore": 1116
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 909,
      "awayId": "tyler",
      "awayScore": 1101
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1176,
      "awayId": "jason",
      "awayScore": 1574
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "titian",
      "homeScore": 673,
      "awayId": "laven",
      "awayScore": 1259
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1065,
      "awayId": "izzy",
      "awayScore": 1375
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1224,
      "awayId": "titian",
      "awayScore": 867
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 718,
      "awayId": "daniel",
      "awayScore": 986
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 919,
      "awayId": "ryan",
      "awayScore": 1182
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 724,
      "awayId": "andrew",
      "awayScore": 1005
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 995,
      "awayId": "izzy",
      "awayScore": 741
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1304,
      "awayId": "tyler",
      "awayScore": 1111
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1136,
      "awayId": "titian",
      "awayScore": 864
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1092,
      "awayId": "nathan",
      "awayScore": 572
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1281,
      "awayId": "izzy",
      "awayScore": 981
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1169,
      "awayId": "laven",
      "awayScore": 1533
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1265,
      "awayId": "ryan",
      "awayScore": 1603
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1364,
      "awayId": "jason",
      "awayScore": 1206
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1599,
      "awayId": "tyler",
      "awayScore": 1262
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1233,
      "awayId": "titian",
      "awayScore": 959
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1305,
      "awayId": "daniel",
      "awayScore": 1490
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1222,
      "awayId": "jason",
      "awayScore": 1301
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1297,
      "awayId": "tyler",
      "awayScore": 1281
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 953,
      "awayId": "nathan",
      "awayScore": 1212
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1632,
      "awayId": "laven",
      "awayScore": 1325
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1122,
      "awayId": "titian",
      "awayScore": 1174
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1388,
      "awayId": "ryan",
      "awayScore": 1879
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1482,
      "awayId": "titian",
      "awayScore": 1102
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1800,
      "awayId": "jason",
      "awayScore": 1119
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1093,
      "awayId": "andrew",
      "awayScore": 1365
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1563,
      "awayId": "tuan",
      "awayScore": 1365
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1038,
      "awayId": "izzy",
      "awayScore": 1572
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 846,
      "awayId": "daniel",
      "awayScore": 1479
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 931,
      "awayId": "laven",
      "awayScore": 1332
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1571,
      "awayId": "tuan",
      "awayScore": 1407
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1535,
      "awayId": "titian",
      "awayScore": 1360
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1184,
      "awayId": "titian",
      "awayScore": 1401
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1781,
      "awayId": "izzy",
      "awayScore": 1648
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 893,
      "awayId": "daniel",
      "awayScore": 1658
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1401,
      "awayId": "jason",
      "awayScore": 813
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1385,
      "awayId": "ryan",
      "awayScore": 1497
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1390,
      "awayId": "laven",
      "awayScore": 1479
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1350,
      "awayId": "izzy",
      "awayScore": 1538
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 941,
      "awayId": "tyler",
      "awayScore": 1176
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1631,
      "awayId": "titian",
      "awayScore": 1055
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1199,
      "awayId": "nathan",
      "awayScore": 990
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1779,
      "awayId": "andrew",
      "awayScore": 1765
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1342,
      "awayId": "tuan",
      "awayScore": 1662
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1533,
      "awayId": "ryan",
      "awayScore": 1995
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1738,
      "awayId": "titian",
      "awayScore": 1530
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1264,
      "awayId": "nathan",
      "awayScore": 1111
    },
    {
      "week": 19,
      "stage": "quarter",
      "homeId": "andrew",
      "homeScore": 3566,
      "awayId": "tyler",
      "awayScore": 2215
    },
    {
      "week": 19,
      "stage": "quarter",
      "homeId": "daniel",
      "homeScore": 2827,
      "awayId": "jason",
      "awayScore": 2488
    },
    {
      "week": 20,
      "stage": "semi",
      "homeId": "laven",
      "homeScore": 2844,
      "awayId": "daniel",
      "awayScore": 2456
    },
    {
      "week": 20,
      "stage": "semi",
      "homeId": "ryan",
      "homeScore": 3486,
      "awayId": "andrew",
      "awayScore": 3265
    },
    {
      "week": 21,
      "stage": "final",
      "homeId": "ryan",
      "homeScore": 3736,
      "awayId": "laven",
      "awayScore": 3510
    }
  ]
};
