// GENERATED by scripts/espn-import.mjs — do not edit by hand.
// Source: ESPN league 803871539, season 2023. Imported 2026-08-31.
//
// Team names, seeds and final placings come straight from ESPN. Everything the
// site displays is derived from the matchup list below.

import type { ImportedSeason } from '@/lib/data/imported';

export const season: ImportedSeason = {
  "id": "2022-23",
  "espnSeasonId": 2023,
  "label": "2022/23",
  "leagueName": "Horn Pub Ligue 1",
  "scoringType": "H2H_POINTS",
  "regularSeasonWeeks": 21,
  "playoffTeams": 6,
  "teams": [
    {
      "managerId": "andrew",
      "espnTeamId": 2,
      "teamName": "Hardens  Hardons",
      "ladderPosition": 1,
      "espn": {
        "wins": 16,
        "losses": 5,
        "ties": 0,
        "pointsFor": 31029,
        "pointsAgainst": 26901,
        "finalRank": 2
      }
    },
    {
      "managerId": "ryan",
      "espnTeamId": 1,
      "teamName": "Boston Long Cocks",
      "ladderPosition": 2,
      "espn": {
        "wins": 13,
        "losses": 7,
        "ties": 1,
        "pointsFor": 31580,
        "pointsAgainst": 29255,
        "finalRank": 4
      }
    },
    {
      "managerId": "daniel",
      "espnTeamId": 5,
      "teamName": "Poolè Partús",
      "ladderPosition": 3,
      "espn": {
        "wins": 13,
        "losses": 8,
        "ties": 0,
        "pointsFor": 30064,
        "pointsAgainst": 28687,
        "finalRank": 1
      }
    },
    {
      "managerId": "luke",
      "espnTeamId": 12,
      "teamName": "suicide Squad",
      "ladderPosition": 4,
      "espn": {
        "wins": 13,
        "losses": 8,
        "ties": 0,
        "pointsFor": 28838,
        "pointsAgainst": 29269,
        "finalRank": 6
      }
    },
    {
      "managerId": "izzy",
      "espnTeamId": 7,
      "teamName": "HP AIRBALLERS",
      "ladderPosition": 5,
      "espn": {
        "wins": 11,
        "losses": 9,
        "ties": 1,
        "pointsFor": 28139,
        "pointsAgainst": 28765,
        "finalRank": 3
      }
    },
    {
      "managerId": "tyler",
      "espnTeamId": 10,
      "teamName": "Gembrook Nets",
      "ladderPosition": 6,
      "espn": {
        "wins": 11,
        "losses": 10,
        "ties": 0,
        "pointsFor": 28375,
        "pointsAgainst": 29627,
        "finalRank": 5
      }
    },
    {
      "managerId": "tuan",
      "espnTeamId": 6,
      "teamName": "Springvale Injury Clinic",
      "ladderPosition": 7,
      "espn": {
        "wins": 10,
        "losses": 11,
        "ties": 0,
        "pointsFor": 29611,
        "pointsAgainst": 28828,
        "finalRank": 7
      }
    },
    {
      "managerId": "nathan",
      "espnTeamId": 9,
      "teamName": "The Bear Cave",
      "ladderPosition": 8,
      "espn": {
        "wins": 10,
        "losses": 11,
        "ties": 0,
        "pointsFor": 29408,
        "pointsAgainst": 27590,
        "finalRank": 8
      }
    },
    {
      "managerId": "laven",
      "espnTeamId": 11,
      "teamName": "Bangholme Billygoats",
      "ladderPosition": 9,
      "espn": {
        "wins": 9,
        "losses": 12,
        "ties": 0,
        "pointsFor": 27522,
        "pointsAgainst": 28969,
        "finalRank": 9
      }
    },
    {
      "managerId": "dylan",
      "espnTeamId": 4,
      "teamName": "Peaky Ballers",
      "ladderPosition": 10,
      "espn": {
        "wins": 9,
        "losses": 12,
        "ties": 0,
        "pointsFor": 29160,
        "pointsAgainst": 29682,
        "finalRank": 10
      }
    },
    {
      "managerId": "jason",
      "espnTeamId": 3,
      "teamName": "Big Bunda Co. Bunda Hospital",
      "ladderPosition": 11,
      "espn": {
        "wins": 5,
        "losses": 16,
        "ties": 0,
        "pointsFor": 25596,
        "pointsAgainst": 28588,
        "finalRank": 12
      }
    },
    {
      "managerId": "imran",
      "espnTeamId": 13,
      "teamName": "Shanghai Sharks",
      "ladderPosition": 12,
      "espn": {
        "wins": 5,
        "losses": 16,
        "ties": 0,
        "pointsFor": 24893,
        "pointsAgainst": 28054,
        "finalRank": 11
      }
    }
  ],
  "matchups": [
    {
      "week": 1,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1488,
      "awayId": "izzy",
      "awayScore": 1255
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1235,
      "awayId": "laven",
      "awayScore": 1043
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1167,
      "awayId": "imran",
      "awayScore": 932
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 963,
      "awayId": "tuan",
      "awayScore": 1124
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1211,
      "awayId": "nathan",
      "awayScore": 840
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1332,
      "awayId": "ryan",
      "awayScore": 1139
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1277,
      "awayId": "daniel",
      "awayScore": 1332
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 938,
      "awayId": "andrew",
      "awayScore": 1538
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1533,
      "awayId": "laven",
      "awayScore": 1275
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1580,
      "awayId": "jason",
      "awayScore": 1568
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1014,
      "awayId": "tyler",
      "awayScore": 1310
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1302,
      "awayId": "tuan",
      "awayScore": 1575
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1495,
      "awayId": "daniel",
      "awayScore": 1254
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 811,
      "awayId": "izzy",
      "awayScore": 1115
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1319,
      "awayId": "dylan",
      "awayScore": 1175
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1261,
      "awayId": "ryan",
      "awayScore": 1442
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1404,
      "awayId": "luke",
      "awayScore": 1480
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1420,
      "awayId": "jason",
      "awayScore": 1117
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1275,
      "awayId": "laven",
      "awayScore": 1331
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1160,
      "awayId": "imran",
      "awayScore": 1075
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1529,
      "awayId": "dylan",
      "awayScore": 1485
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1486,
      "awayId": "nathan",
      "awayScore": 1539
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1690,
      "awayId": "luke",
      "awayScore": 1306
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1323,
      "awayId": "tuan",
      "awayScore": 1296
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1055,
      "awayId": "izzy",
      "awayScore": 1398
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1059,
      "awayId": "andrew",
      "awayScore": 1308
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1455,
      "awayId": "laven",
      "awayScore": 1027
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1492,
      "awayId": "ryan",
      "awayScore": 1437
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1243,
      "awayId": "tyler",
      "awayScore": 1129
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1302,
      "awayId": "tuan",
      "awayScore": 1157
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1550,
      "awayId": "daniel",
      "awayScore": 1262
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1448,
      "awayId": "dylan",
      "awayScore": 1163
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1210,
      "awayId": "imran",
      "awayScore": 1277
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1478,
      "awayId": "izzy",
      "awayScore": 1529
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1127,
      "awayId": "laven",
      "awayScore": 1340
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1448,
      "awayId": "andrew",
      "awayScore": 1119
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1168,
      "awayId": "tuan",
      "awayScore": 1084
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1567,
      "awayId": "ryan",
      "awayScore": 1679
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1329,
      "awayId": "jason",
      "awayScore": 1249
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1548,
      "awayId": "luke",
      "awayScore": 1574
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1273,
      "awayId": "tyler",
      "awayScore": 1443
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1146,
      "awayId": "nathan",
      "awayScore": 1508
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1108,
      "awayId": "imran",
      "awayScore": 1124
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1485,
      "awayId": "laven",
      "awayScore": 1252
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1333,
      "awayId": "andrew",
      "awayScore": 1147
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1463,
      "awayId": "dylan",
      "awayScore": 1494
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1150,
      "awayId": "izzy",
      "awayScore": 1350
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1253,
      "awayId": "daniel",
      "awayScore": 1444
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1398,
      "awayId": "luke",
      "awayScore": 1195
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1507,
      "awayId": "tuan",
      "awayScore": 1307
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1384,
      "awayId": "tyler",
      "awayScore": 1446
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1146,
      "awayId": "ryan",
      "awayScore": 1483
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 874,
      "awayId": "nathan",
      "awayScore": 1370
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 992,
      "awayId": "jason",
      "awayScore": 1249
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 896,
      "awayId": "andrew",
      "awayScore": 1290
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1283,
      "awayId": "izzy",
      "awayScore": 1203
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1061,
      "awayId": "daniel",
      "awayScore": 1188
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1265,
      "awayId": "laven",
      "awayScore": 1111
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1405,
      "awayId": "dylan",
      "awayScore": 1488
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1228,
      "awayId": "imran",
      "awayScore": 1048
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1480,
      "awayId": "ryan",
      "awayScore": 1654
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1573,
      "awayId": "luke",
      "awayScore": 1417
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1597,
      "awayId": "nathan",
      "awayScore": 1535
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1258,
      "awayId": "tuan",
      "awayScore": 1440
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1171,
      "awayId": "jason",
      "awayScore": 1085
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1533,
      "awayId": "tyler",
      "awayScore": 1581
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1433,
      "awayId": "dylan",
      "awayScore": 1555
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1404,
      "awayId": "andrew",
      "awayScore": 1686
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1700,
      "awayId": "daniel",
      "awayScore": 1668
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1644,
      "awayId": "luke",
      "awayScore": 1223
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1665,
      "awayId": "tyler",
      "awayScore": 1115
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1507,
      "awayId": "jason",
      "awayScore": 1284
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1690,
      "awayId": "imran",
      "awayScore": 1066
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1609,
      "awayId": "dylan",
      "awayScore": 1372
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1263,
      "awayId": "luke",
      "awayScore": 1222
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1431,
      "awayId": "izzy",
      "awayScore": 1320
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1352,
      "awayId": "ryan",
      "awayScore": 1612
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1253,
      "awayId": "nathan",
      "awayScore": 1778
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1384,
      "awayId": "andrew",
      "awayScore": 1462
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1483,
      "awayId": "laven",
      "awayScore": 1673
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1224,
      "awayId": "imran",
      "awayScore": 1101
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1190,
      "awayId": "tyler",
      "awayScore": 1425
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1564,
      "awayId": "tuan",
      "awayScore": 1514
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1792,
      "awayId": "nathan",
      "awayScore": 1540
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1400,
      "awayId": "izzy",
      "awayScore": 1177
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1418,
      "awayId": "daniel",
      "awayScore": 1543
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1449,
      "awayId": "andrew",
      "awayScore": 1456
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1267,
      "awayId": "ryan",
      "awayScore": 1551
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1333,
      "awayId": "jason",
      "awayScore": 1186
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1782,
      "awayId": "tyler",
      "awayScore": 1325
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1552,
      "awayId": "dylan",
      "awayScore": 1267
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1329,
      "awayId": "daniel",
      "awayScore": 1692
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1376,
      "awayId": "imran",
      "awayScore": 1015
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1605,
      "awayId": "jason",
      "awayScore": 1291
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1588,
      "awayId": "nathan",
      "awayScore": 1456
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1331,
      "awayId": "luke",
      "awayScore": 1484
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 927,
      "awayId": "daniel",
      "awayScore": 1603
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1373,
      "awayId": "dylan",
      "awayScore": 1317
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1322,
      "awayId": "imran",
      "awayScore": 1344
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1335,
      "awayId": "izzy",
      "awayScore": 1335
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1372,
      "awayId": "laven",
      "awayScore": 1086
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1471,
      "awayId": "andrew",
      "awayScore": 1373
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 2136,
      "awayId": "tuan",
      "awayScore": 1664
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1973,
      "awayId": "ryan",
      "awayScore": 1685
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1666,
      "awayId": "jason",
      "awayScore": 1182
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1324,
      "awayId": "luke",
      "awayScore": 1424
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1861,
      "awayId": "tyler",
      "awayScore": 1693
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1306,
      "awayId": "nathan",
      "awayScore": 1766
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1626,
      "awayId": "nathan",
      "awayScore": 1552
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1331,
      "awayId": "tuan",
      "awayScore": 1747
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1412,
      "awayId": "imran",
      "awayScore": 1074
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1508,
      "awayId": "laven",
      "awayScore": 1485
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1634,
      "awayId": "dylan",
      "awayScore": 1502
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1111,
      "awayId": "daniel",
      "awayScore": 1714
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1536,
      "awayId": "luke",
      "awayScore": 1176
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "imran",
      "homeScore": 1019,
      "awayId": "ryan",
      "awayScore": 1253
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1392,
      "awayId": "nathan",
      "awayScore": 1382
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1079,
      "awayId": "jason",
      "awayScore": 1077
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1466,
      "awayId": "daniel",
      "awayScore": 1256
    },
    {
      "week": 20,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1533,
      "awayId": "dylan",
      "awayScore": 1683
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1806,
      "awayId": "jason",
      "awayScore": 1021
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1045,
      "awayId": "nathan",
      "awayScore": 1662
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1297,
      "awayId": "tuan",
      "awayScore": 1550
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1375,
      "awayId": "izzy",
      "awayScore": 1536
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1416,
      "awayId": "laven",
      "awayScore": 1568
    },
    {
      "week": 21,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1205,
      "awayId": "imran",
      "awayScore": 1487
    },
    {
      "week": 22,
      "stage": "quarter",
      "homeId": "daniel",
      "homeScore": 1647,
      "awayId": "tyler",
      "awayScore": 1366
    },
    {
      "week": 22,
      "stage": "quarter",
      "homeId": "luke",
      "homeScore": 1422,
      "awayId": "izzy",
      "awayScore": 1469
    },
    {
      "week": 23,
      "stage": "semi",
      "homeId": "andrew",
      "homeScore": 1422,
      "awayId": "izzy",
      "awayScore": 1151
    },
    {
      "week": 23,
      "stage": "semi",
      "homeId": "ryan",
      "homeScore": 1329,
      "awayId": "daniel",
      "awayScore": 1674
    },
    {
      "week": 24,
      "stage": "final",
      "homeId": "andrew",
      "homeScore": 1429,
      "awayId": "daniel",
      "awayScore": 1498
    }
  ]
};
