// GENERATED by scripts/espn-import.mjs — do not edit by hand.
// Source: ESPN league 803871539, season 2024. Imported 2026-08-31.
//
// Team names, seeds and final placings come straight from ESPN. Everything the
// site displays is derived from the matchup list below.

import type { ImportedSeason } from '@/lib/data/imported';

export const season: ImportedSeason = {
  "id": "2023-24",
  "espnSeasonId": 2024,
  "label": "2023/24",
  "leagueName": "Horn Pub Ligue 1",
  "scoringType": "H2H_POINTS",
  "regularSeasonWeeks": 19,
  "playoffTeams": 6,
  "teams": [
    {
      "managerId": "laven",
      "espnTeamId": 11,
      "teamName": "LeF***You 3",
      "ladderPosition": 1,
      "espn": {
        "wins": 12,
        "losses": 7,
        "ties": 0,
        "pointsFor": 29402,
        "pointsAgainst": 27598,
        "finalRank": 3
      }
    },
    {
      "managerId": "nathan",
      "espnTeamId": 9,
      "teamName": "Jokic And The Thief",
      "ladderPosition": 2,
      "espn": {
        "wins": 12,
        "losses": 7,
        "ties": 0,
        "pointsFor": 28880,
        "pointsAgainst": 27472,
        "finalRank": 4
      }
    },
    {
      "managerId": "izzy",
      "espnTeamId": 7,
      "teamName": "LUKAKKE",
      "ladderPosition": 3,
      "espn": {
        "wins": 12,
        "losses": 7,
        "ties": 0,
        "pointsFor": 30390,
        "pointsAgainst": 28790,
        "finalRank": 2
      }
    },
    {
      "managerId": "andrew",
      "espnTeamId": 2,
      "teamName": "Paolos Punani",
      "ladderPosition": 4,
      "espn": {
        "wins": 11,
        "losses": 8,
        "ties": 0,
        "pointsFor": 28512,
        "pointsAgainst": 26771,
        "finalRank": 1
      }
    },
    {
      "managerId": "ryan",
      "espnTeamId": 1,
      "teamName": "Boston Long Cocks",
      "ladderPosition": 5,
      "espn": {
        "wins": 11,
        "losses": 8,
        "ties": 0,
        "pointsFor": 29031,
        "pointsAgainst": 29134,
        "finalRank": 6
      }
    },
    {
      "managerId": "luke",
      "espnTeamId": 12,
      "teamName": "Great Barrier Raeves",
      "ladderPosition": 6,
      "espn": {
        "wins": 10,
        "losses": 9,
        "ties": 0,
        "pointsFor": 29718,
        "pointsAgainst": 29227,
        "finalRank": 5
      }
    },
    {
      "managerId": "aaron",
      "espnTeamId": 13,
      "teamName": "The Fun Guys",
      "ladderPosition": 7,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 26735,
        "pointsAgainst": 28240,
        "finalRank": 11
      }
    },
    {
      "managerId": "tuan",
      "espnTeamId": 6,
      "teamName": "Millers Milkers",
      "ladderPosition": 8,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 29614,
        "pointsAgainst": 29753,
        "finalRank": 10
      }
    },
    {
      "managerId": "dylan",
      "espnTeamId": 4,
      "teamName": "Peaky Ballers",
      "ladderPosition": 9,
      "espn": {
        "wins": 8,
        "losses": 11,
        "ties": 0,
        "pointsFor": 29126,
        "pointsAgainst": 29849,
        "finalRank": 9
      }
    },
    {
      "managerId": "tyler",
      "espnTeamId": 10,
      "teamName": "Caught with Pants Down",
      "ladderPosition": 10,
      "espn": {
        "wins": 8,
        "losses": 11,
        "ties": 0,
        "pointsFor": 27487,
        "pointsAgainst": 29452,
        "finalRank": 7
      }
    },
    {
      "managerId": "daniel",
      "espnTeamId": 5,
      "teamName": "The Village Idiots",
      "ladderPosition": 11,
      "espn": {
        "wins": 7,
        "losses": 12,
        "ties": 0,
        "pointsFor": 27457,
        "pointsAgainst": 28486,
        "finalRank": 12
      }
    },
    {
      "managerId": "jason",
      "espnTeamId": 3,
      "teamName": "Big Bunda Co. Bunda Hospital",
      "ladderPosition": 12,
      "espn": {
        "wins": 5,
        "losses": 14,
        "ties": 0,
        "pointsFor": 26697,
        "pointsAgainst": 28277,
        "finalRank": 8
      }
    }
  ],
  "matchups": [
    {
      "week": 1,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 899,
      "awayId": "izzy",
      "awayScore": 1184
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1045,
      "awayId": "laven",
      "awayScore": 1353
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1163,
      "awayId": "aaron",
      "awayScore": 1035
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1074,
      "awayId": "tuan",
      "awayScore": 1258
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1108,
      "awayId": "nathan",
      "awayScore": 1238
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1227,
      "awayId": "ryan",
      "awayScore": 949
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1033,
      "awayId": "andrew",
      "awayScore": 1678
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1344,
      "awayId": "daniel",
      "awayScore": 1329
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1631,
      "awayId": "laven",
      "awayScore": 1674
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1496,
      "awayId": "jason",
      "awayScore": 1498
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1528,
      "awayId": "tyler",
      "awayScore": 1057
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1864,
      "awayId": "tuan",
      "awayScore": 1568
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1366,
      "awayId": "izzy",
      "awayScore": 1511
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1600,
      "awayId": "daniel",
      "awayScore": 1309
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1580,
      "awayId": "dylan",
      "awayScore": 1231
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1409,
      "awayId": "ryan",
      "awayScore": 1437
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1646,
      "awayId": "luke",
      "awayScore": 1355
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1177,
      "awayId": "jason",
      "awayScore": 1510
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1349,
      "awayId": "laven",
      "awayScore": 1910
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1225,
      "awayId": "aaron",
      "awayScore": 1320
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1580,
      "awayId": "dylan",
      "awayScore": 1564
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1147,
      "awayId": "nathan",
      "awayScore": 1536
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1418,
      "awayId": "luke",
      "awayScore": 1608
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1471,
      "awayId": "tuan",
      "awayScore": 1673
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1546,
      "awayId": "laven",
      "awayScore": 1420
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1725,
      "awayId": "izzy",
      "awayScore": 1395
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1305,
      "awayId": "andrew",
      "awayScore": 1557
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1556,
      "awayId": "ryan",
      "awayScore": 1175
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1549,
      "awayId": "tyler",
      "awayScore": 1679
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1423,
      "awayId": "tuan",
      "awayScore": 1476
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1057,
      "awayId": "daniel",
      "awayScore": 1488
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1558,
      "awayId": "dylan",
      "awayScore": 1379
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1681,
      "awayId": "aaron",
      "awayScore": 1407
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1300,
      "awayId": "izzy",
      "awayScore": 1551
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1453,
      "awayId": "laven",
      "awayScore": 1582
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1464,
      "awayId": "andrew",
      "awayScore": 1272
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 907,
      "awayId": "luke",
      "awayScore": 887
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 953,
      "awayId": "tuan",
      "awayScore": 775
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 703,
      "awayId": "ryan",
      "awayScore": 777
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 855,
      "awayId": "jason",
      "awayScore": 734
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1006,
      "awayId": "tyler",
      "awayScore": 872
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1085,
      "awayId": "nathan",
      "awayScore": 913
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1537,
      "awayId": "aaron",
      "awayScore": 1607
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1765,
      "awayId": "laven",
      "awayScore": 1716
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1741,
      "awayId": "andrew",
      "awayScore": 1492
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1834,
      "awayId": "dylan",
      "awayScore": 1676
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1491,
      "awayId": "izzy",
      "awayScore": 1725
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1975,
      "awayId": "daniel",
      "awayScore": 1563
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1273,
      "awayId": "ryan",
      "awayScore": 1431
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1433,
      "awayId": "luke",
      "awayScore": 1642
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1783,
      "awayId": "tuan",
      "awayScore": 1656
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1723,
      "awayId": "tyler",
      "awayScore": 1577
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1643,
      "awayId": "nathan",
      "awayScore": 1658
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1577,
      "awayId": "jason",
      "awayScore": 1388
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1386,
      "awayId": "andrew",
      "awayScore": 1509
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1728,
      "awayId": "izzy",
      "awayScore": 1936
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1862,
      "awayId": "daniel",
      "awayScore": 1344
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1535,
      "awayId": "laven",
      "awayScore": 1370
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1762,
      "awayId": "dylan",
      "awayScore": 1641
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1482,
      "awayId": "aaron",
      "awayScore": 1382
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1627,
      "awayId": "tuan",
      "awayScore": 1603
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1723,
      "awayId": "ryan",
      "awayScore": 1666
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1469,
      "awayId": "luke",
      "awayScore": 1556
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1434,
      "awayId": "nathan",
      "awayScore": 1689
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1545,
      "awayId": "jason",
      "awayScore": 1640
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1377,
      "awayId": "tyler",
      "awayScore": 1426
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1767,
      "awayId": "dylan",
      "awayScore": 1518
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1498,
      "awayId": "andrew",
      "awayScore": 1449
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1516,
      "awayId": "daniel",
      "awayScore": 1438
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1508,
      "awayId": "luke",
      "awayScore": 1359
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1538,
      "awayId": "tyler",
      "awayScore": 1711
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1464,
      "awayId": "jason",
      "awayScore": 1401
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1383,
      "awayId": "aaron",
      "awayScore": 941
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1257,
      "awayId": "dylan",
      "awayScore": 1515
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1374,
      "awayId": "luke",
      "awayScore": 1503
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1658,
      "awayId": "izzy",
      "awayScore": 1378
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1651,
      "awayId": "ryan",
      "awayScore": 1811
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1254,
      "awayId": "nathan",
      "awayScore": 1591
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1389,
      "awayId": "andrew",
      "awayScore": 1359
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1539,
      "awayId": "laven",
      "awayScore": 1571
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1921,
      "awayId": "aaron",
      "awayScore": 1607
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1551,
      "awayId": "tyler",
      "awayScore": 1652
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1501,
      "awayId": "tuan",
      "awayScore": 1643
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1682,
      "awayId": "nathan",
      "awayScore": 1514
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1640,
      "awayId": "daniel",
      "awayScore": 1501
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1839,
      "awayId": "izzy",
      "awayScore": 1801
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1419,
      "awayId": "andrew",
      "awayScore": 1556
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1760,
      "awayId": "ryan",
      "awayScore": 1821
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1809,
      "awayId": "jason",
      "awayScore": 1705
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1953,
      "awayId": "tyler",
      "awayScore": 1826
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1763,
      "awayId": "dylan",
      "awayScore": 1860
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1597,
      "awayId": "daniel",
      "awayScore": 1491
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1491,
      "awayId": "aaron",
      "awayScore": 1076
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1635,
      "awayId": "jason",
      "awayScore": 1317
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1263,
      "awayId": "nathan",
      "awayScore": 1458
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1300,
      "awayId": "luke",
      "awayScore": 1627
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 2017,
      "awayId": "daniel",
      "awayScore": 2159
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 2212,
      "awayId": "dylan",
      "awayScore": 2035
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1791,
      "awayId": "aaron",
      "awayScore": 2212
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1976,
      "awayId": "izzy",
      "awayScore": 1870
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 2342,
      "awayId": "laven",
      "awayScore": 1808
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1462,
      "awayId": "andrew",
      "awayScore": 2159
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1582,
      "awayId": "luke",
      "awayScore": 1707
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1661,
      "awayId": "tuan",
      "awayScore": 1446
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1567,
      "awayId": "ryan",
      "awayScore": 1434
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1425,
      "awayId": "jason",
      "awayScore": 1495
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1829,
      "awayId": "tyler",
      "awayScore": 1362
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1650,
      "awayId": "nathan",
      "awayScore": 1190
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1717,
      "awayId": "nathan",
      "awayScore": 1341
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1789,
      "awayId": "tuan",
      "awayScore": 1491
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1310,
      "awayId": "aaron",
      "awayScore": 1407
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1797,
      "awayId": "laven",
      "awayScore": 1645
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1748,
      "awayId": "dylan",
      "awayScore": 2080
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1513,
      "awayId": "daniel",
      "awayScore": 1672
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "andrew",
      "homeScore": 1634,
      "awayId": "ryan",
      "awayScore": 1549
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "izzy",
      "homeScore": 1849,
      "awayId": "luke",
      "awayScore": 1169
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "laven",
      "homeScore": 1549,
      "awayId": "andrew",
      "awayScore": 1838
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "nathan",
      "homeScore": 1592,
      "awayId": "izzy",
      "awayScore": 1765
    },
    {
      "week": 22,
      "stage": "final",
      "homeId": "izzy",
      "homeScore": 1770,
      "awayId": "andrew",
      "awayScore": 1846
    }
  ]
};
