// GENERATED by scripts/espn-import.mjs — do not edit by hand.
// Source: ESPN league 803871539, season 2025. Imported 2026-08-31.
//
// Team names, seeds and final placings come straight from ESPN. Everything the
// site displays is derived from the matchup list below.

import type { ImportedSeason } from '@/lib/data/imported';

export const season: ImportedSeason = {
  "id": "2024-25",
  "espnSeasonId": 2025,
  "label": "2024/25",
  "leagueName": "Horn Pub Ligue 1",
  "scoringType": "H2H_POINTS",
  "regularSeasonWeeks": 19,
  "playoffTeams": 6,
  "teams": [
    {
      "managerId": "andrew",
      "espnTeamId": 2,
      "teamName": "FRED AGAIN",
      "ladderPosition": 1,
      "espn": {
        "wins": 16,
        "losses": 3,
        "ties": 0,
        "pointsFor": 30684,
        "pointsAgainst": 27029,
        "finalRank": 2
      }
    },
    {
      "managerId": "dylan",
      "espnTeamId": 4,
      "teamName": "Lukas puppies",
      "ladderPosition": 2,
      "espn": {
        "wins": 15,
        "losses": 4,
        "ties": 0,
        "pointsFor": 29576,
        "pointsAgainst": 26496,
        "finalRank": 3
      }
    },
    {
      "managerId": "tuan",
      "espnTeamId": 6,
      "teamName": "Tylers is an Ape",
      "ladderPosition": 3,
      "espn": {
        "wins": 12,
        "losses": 7,
        "ties": 0,
        "pointsFor": 27881,
        "pointsAgainst": 27823,
        "finalRank": 1
      }
    },
    {
      "managerId": "tyler",
      "espnTeamId": 10,
      "teamName": "Ferg in ya hole",
      "ladderPosition": 4,
      "espn": {
        "wins": 10,
        "losses": 9,
        "ties": 0,
        "pointsFor": 28046,
        "pointsAgainst": 27694,
        "finalRank": 4
      }
    },
    {
      "managerId": "luke",
      "espnTeamId": 12,
      "teamName": "Cade and em",
      "ladderPosition": 5,
      "espn": {
        "wins": 10,
        "losses": 9,
        "ties": 0,
        "pointsFor": 28612,
        "pointsAgainst": 28203,
        "finalRank": 5
      }
    },
    {
      "managerId": "daniel",
      "espnTeamId": 5,
      "teamName": "Doungies Downers",
      "ladderPosition": 6,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 28526,
        "pointsAgainst": 27912,
        "finalRank": 6
      }
    },
    {
      "managerId": "izzy",
      "espnTeamId": 7,
      "teamName": "AFK",
      "ladderPosition": 7,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 29881,
        "pointsAgainst": 28450,
        "finalRank": 10
      }
    },
    {
      "managerId": "laven",
      "espnTeamId": 11,
      "teamName": "LeAntMan",
      "ladderPosition": 8,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 26903,
        "pointsAgainst": 28032,
        "finalRank": 12
      }
    },
    {
      "managerId": "ryan",
      "espnTeamId": 1,
      "teamName": "Giddey Fiddler's",
      "ladderPosition": 9,
      "espn": {
        "wins": 8,
        "losses": 11,
        "ties": 0,
        "pointsFor": 27109,
        "pointsAgainst": 28236,
        "finalRank": 7
      }
    },
    {
      "managerId": "aaron",
      "espnTeamId": 13,
      "teamName": "My Shaila",
      "ladderPosition": 10,
      "espn": {
        "wins": 6,
        "losses": 13,
        "ties": 0,
        "pointsFor": 27885,
        "pointsAgainst": 27691,
        "finalRank": 11
      }
    },
    {
      "managerId": "nathan",
      "espnTeamId": 9,
      "teamName": "The Bear Cave",
      "ladderPosition": 11,
      "espn": {
        "wins": 6,
        "losses": 13,
        "ties": 0,
        "pointsFor": 23680,
        "pointsAgainst": 28248,
        "finalRank": 8
      }
    },
    {
      "managerId": "jason",
      "espnTeamId": 3,
      "teamName": "Big Bunda Co. Bunda Hospital",
      "ladderPosition": 12,
      "espn": {
        "wins": 4,
        "losses": 15,
        "ties": 0,
        "pointsFor": 26160,
        "pointsAgainst": 29129,
        "finalRank": 9
      }
    }
  ],
  "matchups": [
    {
      "week": 1,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1187,
      "awayId": "izzy",
      "awayScore": 1317
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 957,
      "awayId": "andrew",
      "awayScore": 1388
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1007,
      "awayId": "jason",
      "awayScore": 837
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1390,
      "awayId": "luke",
      "awayScore": 1179
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1127,
      "awayId": "daniel",
      "awayScore": 1183
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1284,
      "awayId": "aaron",
      "awayScore": 1283
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1424,
      "awayId": "dylan",
      "awayScore": 1647
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1500,
      "awayId": "izzy",
      "awayScore": 2022
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1552,
      "awayId": "nathan",
      "awayScore": 1584
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1455,
      "awayId": "ryan",
      "awayScore": 1682
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1386,
      "awayId": "laven",
      "awayScore": 1427
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1588,
      "awayId": "tyler",
      "awayScore": 1523
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1361,
      "awayId": "andrew",
      "awayScore": 1716
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1782,
      "awayId": "tuan",
      "awayScore": 1501
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1664,
      "awayId": "luke",
      "awayScore": 1845
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1524,
      "awayId": "jason",
      "awayScore": 1618
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1558,
      "awayId": "nathan",
      "awayScore": 1384
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1568,
      "awayId": "daniel",
      "awayScore": 1595
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1696,
      "awayId": "tuan",
      "awayScore": 1524
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1697,
      "awayId": "ryan",
      "awayScore": 1454
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1494,
      "awayId": "izzy",
      "awayScore": 1419
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1610,
      "awayId": "aaron",
      "awayScore": 1587
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1487,
      "awayId": "laven",
      "awayScore": 1730
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1344,
      "awayId": "dylan",
      "awayScore": 1768
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1628,
      "awayId": "jason",
      "awayScore": 1092
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1281,
      "awayId": "daniel",
      "awayScore": 1182
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1633,
      "awayId": "nathan",
      "awayScore": 1536
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1462,
      "awayId": "ryan",
      "awayScore": 1339
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 994,
      "awayId": "luke",
      "awayScore": 1691
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1376,
      "awayId": "andrew",
      "awayScore": 1512
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1705,
      "awayId": "dylan",
      "awayScore": 1512
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1673,
      "awayId": "laven",
      "awayScore": 1555
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1589,
      "awayId": "tuan",
      "awayScore": 1590
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1443,
      "awayId": "tyler",
      "awayScore": 1757
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1450,
      "awayId": "aaron",
      "awayScore": 1536
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1475,
      "awayId": "izzy",
      "awayScore": 1550
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1727,
      "awayId": "ryan",
      "awayScore": 1935
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1507,
      "awayId": "andrew",
      "awayScore": 1671
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1588,
      "awayId": "luke",
      "awayScore": 1544
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1693,
      "awayId": "laven",
      "awayScore": 1412
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1502,
      "awayId": "nathan",
      "awayScore": 1505
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1836,
      "awayId": "jason",
      "awayScore": 1679
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 510,
      "awayId": "daniel",
      "awayScore": 983
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 881,
      "awayId": "dylan",
      "awayScore": 952
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 790,
      "awayId": "aaron",
      "awayScore": 742
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 651,
      "awayId": "andrew",
      "awayScore": 776
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 487,
      "awayId": "tyler",
      "awayScore": 1023
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 777,
      "awayId": "tuan",
      "awayScore": 963
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1314,
      "awayId": "izzy",
      "awayScore": 1274
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1265,
      "awayId": "jason",
      "awayScore": 854
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1122,
      "awayId": "luke",
      "awayScore": 1226
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 921,
      "awayId": "nathan",
      "awayScore": 940
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 940,
      "awayId": "laven",
      "awayScore": 933
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1159,
      "awayId": "ryan",
      "awayScore": 930
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1426,
      "awayId": "daniel",
      "awayScore": 1891
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1422,
      "awayId": "tuan",
      "awayScore": 1560
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1299,
      "awayId": "luke",
      "awayScore": 1487
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1612,
      "awayId": "tyler",
      "awayScore": 1611
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1035,
      "awayId": "andrew",
      "awayScore": 1531
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1086,
      "awayId": "dylan",
      "awayScore": 1475
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1641,
      "awayId": "ryan",
      "awayScore": 1229
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1872,
      "awayId": "jason",
      "awayScore": 1501
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1471,
      "awayId": "laven",
      "awayScore": 1353
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1492,
      "awayId": "nathan",
      "awayScore": 1475
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1591,
      "awayId": "aaron",
      "awayScore": 1462
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1614,
      "awayId": "izzy",
      "awayScore": 1516
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1466,
      "awayId": "tyler",
      "awayScore": 1308
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1925,
      "awayId": "laven",
      "awayScore": 1575
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1410,
      "awayId": "tuan",
      "awayScore": 1654
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1335,
      "awayId": "dylan",
      "awayScore": 1552
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1686,
      "awayId": "nathan",
      "awayScore": 1338
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1696,
      "awayId": "ryan",
      "awayScore": 1323
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1779,
      "awayId": "aaron",
      "awayScore": 1642
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1402,
      "awayId": "andrew",
      "awayScore": 1862
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1526,
      "awayId": "luke",
      "awayScore": 1632
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1301,
      "awayId": "daniel",
      "awayScore": 1254
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1366,
      "awayId": "jason",
      "awayScore": 1350
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1527,
      "awayId": "tuan",
      "awayScore": 1716
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1451,
      "awayId": "aaron",
      "awayScore": 1388
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1286,
      "awayId": "tyler",
      "awayScore": 1347
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1157,
      "awayId": "laven",
      "awayScore": 1362
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1613,
      "awayId": "izzy",
      "awayScore": 1468
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1305,
      "awayId": "ryan",
      "awayScore": 1513
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1474,
      "awayId": "dylan",
      "awayScore": 1512
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1327,
      "awayId": "luke",
      "awayScore": 1639
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1379,
      "awayId": "tyler",
      "awayScore": 1399
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1697,
      "awayId": "jason",
      "awayScore": 1318
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1615,
      "awayId": "nathan",
      "awayScore": 1303
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1577,
      "awayId": "daniel",
      "awayScore": 1386
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1717,
      "awayId": "andrew",
      "awayScore": 1983
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1502,
      "awayId": "tyler",
      "awayScore": 1567
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1520,
      "awayId": "dylan",
      "awayScore": 1976
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1080,
      "awayId": "aaron",
      "awayScore": 1858
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1660,
      "awayId": "tuan",
      "awayScore": 1754
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 861,
      "awayId": "izzy",
      "awayScore": 1988
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1605,
      "awayId": "laven",
      "awayScore": 1612
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1995,
      "awayId": "nathan",
      "awayScore": 1248
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 2156,
      "awayId": "andrew",
      "awayScore": 1715
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 2395,
      "awayId": "ryan",
      "awayScore": 2025
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1651,
      "awayId": "daniel",
      "awayScore": 1952
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1816,
      "awayId": "jason",
      "awayScore": 1814
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1827,
      "awayId": "luke",
      "awayScore": 1798
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1749,
      "awayId": "daniel",
      "awayScore": 1605
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1751,
      "awayId": "tyler",
      "awayScore": 1595
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1443,
      "awayId": "izzy",
      "awayScore": 1822
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1429,
      "awayId": "dylan",
      "awayScore": 1803
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1051,
      "awayId": "tuan",
      "awayScore": 1501
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1542,
      "awayId": "aaron",
      "awayScore": 1431
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1288,
      "awayId": "laven",
      "awayScore": 1364
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 2096,
      "awayId": "luke",
      "awayScore": 1591
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1856,
      "awayId": "izzy",
      "awayScore": 1754
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1835,
      "awayId": "jason",
      "awayScore": 1705
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1369,
      "awayId": "ryan",
      "awayScore": 1303
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1381,
      "awayId": "nathan",
      "awayScore": 1383
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "tuan",
      "homeScore": 1795,
      "awayId": "daniel",
      "awayScore": 1738
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "tyler",
      "homeScore": 1675,
      "awayId": "luke",
      "awayScore": 1327
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "andrew",
      "homeScore": 1599,
      "awayId": "tyler",
      "awayScore": 1340
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "dylan",
      "homeScore": 1744,
      "awayId": "tuan",
      "awayScore": 1858
    },
    {
      "week": 22,
      "stage": "final",
      "homeId": "andrew",
      "homeScore": 1498,
      "awayId": "tuan",
      "awayScore": 1717
    }
  ]
};
