// GENERATED by scripts/espn-import.mjs — do not edit by hand.
// Source: ESPN league 803871539, season 2026. Imported 2026-08-31.
//
// Team names, seeds and final placings come straight from ESPN. Everything the
// site displays is derived from the matchup list below.

import type { ImportedSeason } from '@/lib/data/imported';

export const season: ImportedSeason = {
  "id": "2025-26",
  "espnSeasonId": 2026,
  "label": "2025/26",
  "leagueName": "Horn Pub Ligue 1",
  "scoringType": "H2H_POINTS",
  "regularSeasonWeeks": 19,
  "playoffTeams": 6,
  "teams": [
    {
      "managerId": "ryan",
      "espnTeamId": 1,
      "teamName": "Giddey Fiddler's",
      "ladderPosition": 1,
      "espn": {
        "wins": 16,
        "losses": 3,
        "ties": 0,
        "pointsFor": 30336,
        "pointsAgainst": 26207,
        "finalRank": 2
      }
    },
    {
      "managerId": "luke",
      "espnTeamId": 12,
      "teamName": "Luka Doncic",
      "ladderPosition": 2,
      "espn": {
        "wins": 15,
        "losses": 4,
        "ties": 0,
        "pointsFor": 28138,
        "pointsAgainst": 26927,
        "finalRank": 3
      }
    },
    {
      "managerId": "andrew",
      "espnTeamId": 2,
      "teamName": "EDEYS NUTZ",
      "ladderPosition": 3,
      "espn": {
        "wins": 14,
        "losses": 5,
        "ties": 0,
        "pointsFor": 30358,
        "pointsAgainst": 26052,
        "finalRank": 1
      }
    },
    {
      "managerId": "dylan",
      "espnTeamId": 4,
      "teamName": "Downfall dyson",
      "ladderPosition": 4,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 27476,
        "pointsAgainst": 26255,
        "finalRank": 4
      }
    },
    {
      "managerId": "aaron",
      "espnTeamId": 13,
      "teamName": "Big Kats Home",
      "ladderPosition": 5,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 26975,
        "pointsAgainst": 27766,
        "finalRank": 6
      }
    },
    {
      "managerId": "laven",
      "espnTeamId": 11,
      "teamName": "LeFartingSensation",
      "ladderPosition": 6,
      "espn": {
        "wins": 9,
        "losses": 10,
        "ties": 0,
        "pointsFor": 26142,
        "pointsAgainst": 27334,
        "finalRank": 5
      }
    },
    {
      "managerId": "daniel",
      "espnTeamId": 5,
      "teamName": "Frederick Rise Cream3.14159's",
      "ladderPosition": 7,
      "espn": {
        "wins": 8,
        "losses": 11,
        "ties": 0,
        "pointsFor": 27484,
        "pointsAgainst": 26950,
        "finalRank": 9
      }
    },
    {
      "managerId": "tuan",
      "espnTeamId": 6,
      "teamName": "Shai's Angels",
      "ladderPosition": 8,
      "espn": {
        "wins": 7,
        "losses": 12,
        "ties": 0,
        "pointsFor": 26927,
        "pointsAgainst": 28198,
        "finalRank": 8
      }
    },
    {
      "managerId": "izzy",
      "espnTeamId": 7,
      "teamName": "a sarr dude",
      "ladderPosition": 9,
      "espn": {
        "wins": 7,
        "losses": 12,
        "ties": 0,
        "pointsFor": 26688,
        "pointsAgainst": 28465,
        "finalRank": 7
      }
    },
    {
      "managerId": "nathan",
      "espnTeamId": 9,
      "teamName": "Shake Time",
      "ladderPosition": 10,
      "espn": {
        "wins": 7,
        "losses": 12,
        "ties": 0,
        "pointsFor": 26213,
        "pointsAgainst": 27871,
        "finalRank": 12
      }
    },
    {
      "managerId": "tyler",
      "espnTeamId": 10,
      "teamName": "WaitingForAFL",
      "ladderPosition": 11,
      "espn": {
        "wins": 7,
        "losses": 12,
        "ties": 0,
        "pointsFor": 25093,
        "pointsAgainst": 27514,
        "finalRank": 10
      }
    },
    {
      "managerId": "jason",
      "espnTeamId": 3,
      "teamName": "Big Bunda Ballers",
      "ladderPosition": 12,
      "espn": {
        "wins": 6,
        "losses": 13,
        "ties": 0,
        "pointsFor": 26119,
        "pointsAgainst": 28410,
        "finalRank": 11
      }
    }
  ],
  "matchups": [
    {
      "week": 1,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1455,
      "awayId": "izzy",
      "awayScore": 1071
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1085,
      "awayId": "luke",
      "awayScore": 1141
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1205,
      "awayId": "nathan",
      "awayScore": 1126
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1331,
      "awayId": "aaron",
      "awayScore": 1182
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1132,
      "awayId": "andrew",
      "awayScore": 1299
    },
    {
      "week": 1,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 853,
      "awayId": "ryan",
      "awayScore": 1194
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1464,
      "awayId": "jason",
      "awayScore": 1593
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1488,
      "awayId": "dylan",
      "awayScore": 1752
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1717,
      "awayId": "tyler",
      "awayScore": 1217
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1241,
      "awayId": "tuan",
      "awayScore": 1348
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1249,
      "awayId": "andrew",
      "awayScore": 1966
    },
    {
      "week": 2,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1630,
      "awayId": "luke",
      "awayScore": 1509
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1441,
      "awayId": "nathan",
      "awayScore": 1426
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1651,
      "awayId": "laven",
      "awayScore": 1336
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1350,
      "awayId": "ryan",
      "awayScore": 1799
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1687,
      "awayId": "tuan",
      "awayScore": 1493
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1607,
      "awayId": "daniel",
      "awayScore": 1028
    },
    {
      "week": 3,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1505,
      "awayId": "dylan",
      "awayScore": 1435
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1642,
      "awayId": "izzy",
      "awayScore": 1092
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1489,
      "awayId": "andrew",
      "awayScore": 1876
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1258,
      "awayId": "laven",
      "awayScore": 1523
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1729,
      "awayId": "daniel",
      "awayScore": 1383
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1377,
      "awayId": "aaron",
      "awayScore": 1767
    },
    {
      "week": 4,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1405,
      "awayId": "luke",
      "awayScore": 1540
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1386,
      "awayId": "andrew",
      "awayScore": 1746
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1329,
      "awayId": "tyler",
      "awayScore": 1460
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1735,
      "awayId": "ryan",
      "awayScore": 1786
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1139,
      "awayId": "luke",
      "awayScore": 1540
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1582,
      "awayId": "jason",
      "awayScore": 1284
    },
    {
      "week": 5,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1426,
      "awayId": "nathan",
      "awayScore": 1555
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1413,
      "awayId": "laven",
      "awayScore": 1430
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1331,
      "awayId": "tuan",
      "awayScore": 1381
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1298,
      "awayId": "aaron",
      "awayScore": 1477
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1439,
      "awayId": "andrew",
      "awayScore": 1852
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1717,
      "awayId": "nathan",
      "awayScore": 1241
    },
    {
      "week": 6,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1434,
      "awayId": "jason",
      "awayScore": 1377
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1771,
      "awayId": "daniel",
      "awayScore": 1701
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1877,
      "awayId": "izzy",
      "awayScore": 1279
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1445,
      "awayId": "luke",
      "awayScore": 1608
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1417,
      "awayId": "dylan",
      "awayScore": 1630
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1515,
      "awayId": "tyler",
      "awayScore": 1531
    },
    {
      "week": 7,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1186,
      "awayId": "ryan",
      "awayScore": 1719
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1196,
      "awayId": "andrew",
      "awayScore": 1038
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 814,
      "awayId": "aaron",
      "awayScore": 898
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 997,
      "awayId": "jason",
      "awayScore": 974
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 758,
      "awayId": "nathan",
      "awayScore": 727
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 953,
      "awayId": "laven",
      "awayScore": 948
    },
    {
      "week": 8,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 758,
      "awayId": "tuan",
      "awayScore": 712
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1159,
      "awayId": "ryan",
      "awayScore": 1275
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1105,
      "awayId": "dylan",
      "awayScore": 1461
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1229,
      "awayId": "daniel",
      "awayScore": 940
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1372,
      "awayId": "tyler",
      "awayScore": 1130
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1298,
      "awayId": "izzy",
      "awayScore": 1359
    },
    {
      "week": 9,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1247,
      "awayId": "luke",
      "awayScore": 1260
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1731,
      "awayId": "nathan",
      "awayScore": 1033
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1328,
      "awayId": "jason",
      "awayScore": 1243
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1514,
      "awayId": "tuan",
      "awayScore": 1386
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1437,
      "awayId": "laven",
      "awayScore": 1294
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1481,
      "awayId": "andrew",
      "awayScore": 1665
    },
    {
      "week": 10,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1668,
      "awayId": "aaron",
      "awayScore": 1326
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1634,
      "awayId": "luke",
      "awayScore": 1687
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1692,
      "awayId": "tyler",
      "awayScore": 1663
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1489,
      "awayId": "ryan",
      "awayScore": 1623
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1651,
      "awayId": "izzy",
      "awayScore": 1559
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1730,
      "awayId": "dylan",
      "awayScore": 1618
    },
    {
      "week": 11,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1423,
      "awayId": "daniel",
      "awayScore": 1843
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1499,
      "awayId": "laven",
      "awayScore": 1409
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1595,
      "awayId": "tuan",
      "awayScore": 1713
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1454,
      "awayId": "daniel",
      "awayScore": 1837
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1484,
      "awayId": "dylan",
      "awayScore": 1426
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1659,
      "awayId": "jason",
      "awayScore": 1443
    },
    {
      "week": 12,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1490,
      "awayId": "tyler",
      "awayScore": 1468
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1328,
      "awayId": "nathan",
      "awayScore": 999
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1250,
      "awayId": "daniel",
      "awayScore": 1560
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1125,
      "awayId": "aaron",
      "awayScore": 1609
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1526,
      "awayId": "ryan",
      "awayScore": 1465
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1522,
      "awayId": "laven",
      "awayScore": 1684
    },
    {
      "week": 13,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1127,
      "awayId": "izzy",
      "awayScore": 1554
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1500,
      "awayId": "luke",
      "awayScore": 1542
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1371,
      "awayId": "tyler",
      "awayScore": 856
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1612,
      "awayId": "andrew",
      "awayScore": 1568
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1749,
      "awayId": "aaron",
      "awayScore": 1430
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1705,
      "awayId": "izzy",
      "awayScore": 1547
    },
    {
      "week": 14,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1876,
      "awayId": "jason",
      "awayScore": 1351
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1591,
      "awayId": "tuan",
      "awayScore": 1688
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1635,
      "awayId": "jason",
      "awayScore": 1298
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1367,
      "awayId": "ryan",
      "awayScore": 1660
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1794,
      "awayId": "dylan",
      "awayScore": 1456
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1354,
      "awayId": "nathan",
      "awayScore": 1643
    },
    {
      "week": 15,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1926,
      "awayId": "tyler",
      "awayScore": 1621
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1584,
      "awayId": "aaron",
      "awayScore": 1059
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1351,
      "awayId": "laven",
      "awayScore": 1145
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1573,
      "awayId": "izzy",
      "awayScore": 1469
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1210,
      "awayId": "tuan",
      "awayScore": 1283
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1732,
      "awayId": "dylan",
      "awayScore": 1080
    },
    {
      "week": 16,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1060,
      "awayId": "daniel",
      "awayScore": 1519
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1502,
      "awayId": "laven",
      "awayScore": 1636
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1874,
      "awayId": "tuan",
      "awayScore": 1666
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1636,
      "awayId": "aaron",
      "awayScore": 1721
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1476,
      "awayId": "andrew",
      "awayScore": 1979
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 2032,
      "awayId": "nathan",
      "awayScore": 1821
    },
    {
      "week": 17,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1715,
      "awayId": "jason",
      "awayScore": 1742
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "aaron",
      "homeScore": 1269,
      "awayId": "daniel",
      "awayScore": 1155
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "andrew",
      "homeScore": 1366,
      "awayId": "izzy",
      "awayScore": 1247
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "jason",
      "homeScore": 1430,
      "awayId": "luke",
      "awayScore": 1688
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "laven",
      "homeScore": 1085,
      "awayId": "dylan",
      "awayScore": 1684
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "nathan",
      "homeScore": 1423,
      "awayId": "tyler",
      "awayScore": 1329
    },
    {
      "week": 18,
      "stage": "regular",
      "homeId": "tuan",
      "homeScore": 1788,
      "awayId": "ryan",
      "awayScore": 1626
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "daniel",
      "homeScore": 1537,
      "awayId": "andrew",
      "awayScore": 1536
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "dylan",
      "homeScore": 1504,
      "awayId": "aaron",
      "awayScore": 1292
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "izzy",
      "homeScore": 1612,
      "awayId": "jason",
      "awayScore": 1364
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "luke",
      "homeScore": 1397,
      "awayId": "nathan",
      "awayScore": 1551
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "ryan",
      "homeScore": 1720,
      "awayId": "laven",
      "awayScore": 1092
    },
    {
      "week": 19,
      "stage": "regular",
      "homeId": "tyler",
      "homeScore": 1293,
      "awayId": "tuan",
      "awayScore": 1280
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "andrew",
      "homeScore": 2147,
      "awayId": "laven",
      "awayScore": 1394
    },
    {
      "week": 20,
      "stage": "quarter",
      "homeId": "dylan",
      "homeScore": 1508,
      "awayId": "aaron",
      "awayScore": 1445
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "luke",
      "homeScore": 1678,
      "awayId": "andrew",
      "awayScore": 2113
    },
    {
      "week": 21,
      "stage": "semi",
      "homeId": "ryan",
      "homeScore": 1750,
      "awayId": "dylan",
      "awayScore": 1339
    },
    {
      "week": 22,
      "stage": "final",
      "homeId": "ryan",
      "homeScore": 2046,
      "awayId": "andrew",
      "awayScore": 2056
    }
  ]
};
